Update test-mac.yml

diff --git a/.github/workflows/test-mac.yml b/.github/workflows/test-mac.yml
--- a/.github/workflows/test-mac.yml
+++ b/.github/workflows/test-mac.yml
@@ -28,10 +28,17 @@ jobs:
       - name: Install docker
         #uses: docker-practice/actions-setup-docker@master
         run: |
-            brew install docker docker-machine
-            docker-machine create --driver virtualbox default
-            docker-machine env default
-            eval "$(docker-machine env default)"
+            #brew install docker docker-machine
+            #docker-machine create --driver virtualbox default
+            #docker-machine env default
+            #eval "$(docker-machine env default)"
+            
+            HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+            sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+            open -a /Applications/Docker.app --args --unattended --accept-license
+            echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+            while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
+
 
       - name: Create image ${{ matrix.config.name }}
         run:  docker buildx build -t ${{ matrix.config.repo }}:${{ matrix.config.tag }} -f Dockerfile-${{ matrix.config.name }} .
